[package]
name = "supports-hyperlinks"
version = "3.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
description = "Detects whether a terminal supports rendering hyperlinks."
repository = "https://github.com/zkat/supports-hyperlinks"
documentation = "https://docs.rs/supports-hyperlinks"
license = "Apache-2.0"
readme = "README.md"
edition = "2021"
rust-version = "1.70.0"
